# Ptwist Network

OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: MEDSOS
    Domain: MEDSOS.example.com
    Template:
      Count: 2
    Users:
      Count: 0
  - Name: HSLU
    Domain: HSLU.example.com
    Template:
      Count: 4
    Users:
      Count: 0
  - Name: BLUECITY
    Domain: BLUECITY.example.com
    Template:
      Count: 4
    Users:
      Count: 0
